### ISSUE TITLE
Category setting not stored

### ISSUE THREAD

**Issue by radamazone** [Sysix-Coding/asd_news#17]
In the backend the category according to the newsarticle is not stored correctly.

**Comment by Sysix-Coding** [comment]
Which version? Can you fixed it?

**Comment by radamazone** [comment]
Hello it is in the frontend, the category filter does not work there is no news shown if a category is selected. Version 1.4 DEV.

**Comment by Sysix-Coding** [comment]
okay, thanks! i will look on this.
You can look on the Meta-Field "category" if the radio-input right set on **defined SQL column**.

**Comment by radamazone** [comment]
Das sind meine Einste
![asd-einst](https://cloud.githubusercontent.com/assets/10929248/6146536/2ba6a1a6-b1ee-11e4-8d8d-336d57c007fa.png)
llungen

**Comment by radamazone** [comment]
If you like an Account for the website, to test, please tell me.

**Comment by Sysix-Coding** [comment]
Setzt bei "Definierte SQL Spalte" als Kategorie :) Muss ich dann noch als Default setzen in der Config

**Comment by radamazone** [comment]
Danke hab ich gemacht, was muss ich noch in der Config ergänzen? Weil es funktioniert noch nicht.

**Comment by Sysix-Coding** [comment]
noramlerweiße müsste im data/asd_news/config.json unter sql->category jetzt asd_category stehen

**Comment by Sysix-Coding** [comment]
Ich konnte den Fehler nicht festellen. Kannst du nochmal versuchen das Adddon de/re-installieren? Und nochmal alle Module neu Anlegen? Geht ja via Knopfdruck unter Einstellungen

**Comment by Sysix-Coding** [comment]
Unter gewissen Umständen, wurde die SQL Einträge wieder gelöscht.
Schau doch bitte ob nun mit den neusten Eintrag funktioniert.
Hier war der Fehler: https://github.com/Sysix-Coding/asd_news/commit/7a73864c050e7d1853a9de15c6472a477945330d#diff-05ba602faa747e9b4e9243910130e80cR71
