### ISSUE TITLE
Admin sollte immer alle Benutzerrechte haben

### ISSUE THREAD

**Issue by RexDude** [Sysix-Coding/asd_news#22]
Man guckt ein bisschen blöd wenn man die Meldung bekommt man muss einen News Artikel einstellen und dann weiss man net wo und findet es erst heraus wenn man die FAQ studiert hat.

**Comment by RexDude** [comment]
Desweiteren interessiert FAQ eigentlich keinen Redakteur...weil ja nur technischer kram drinsteht.

**Comment by Sysix-Coding** [comment]
https://github.com/Sysix-Coding/asd_news/commit/09668931a83f93b6e33eefee95ddbb37de63e025
F.A.Q. ist eher nebensächtlich :)

**Comment by RexDude** [comment]
Sehe ich auch so ;)
Ein Hilfe Menüpunkt mit Readme, Changelog und FAQ würde ishc bei dir auch gut machen. Dann kann man die Codebeispiele direkt im Backend studieren ;)
Nur so am Rande...

**Comment by Sysix-Coding** [comment]
Was aufeinmal los mit dir? :D Interesse in das AddOn bekommen oder wieso so viele Wünsche und Verbesserungsvorschläge?

**Comment by RexDude** [comment]
Ich hab halt mal ein bisschen getestet heut :)
Ist ein cooles Teil, deshalb bring ich mich bisschen ein :)
