### ISSUE TITLE
Unveröffentlichen Farben

### ISSUE THREAD

**Issue by RexDude** [Sysix-Coding/asd_news#23]
Also das finde ich verwirrend. Zuerstmal versuchst du hier das on/offline verhalten nachzuahmen was ja prinzipiell gut ist. Zwei Dinge passen hier aber nicht so ganz:

1. Du benutz hier Verben die einen Status reflektieren sollen. on offline sind Adjektive was dazu viel besser passt.
2. Grün ist für mich ein positive Farbe und ich würde hier denken die News ist bereits veröffentlicht. Tatsächlich muss man aber von grün auf rot schalten (was in REDAXO offline bedeutet) um bei dir online zu haben.

Vorschlag:

Nach News anlegen: Status: rot "unveröffentlicht"
Nach Klick auf rot "unveröffentlicht": Status: grün "veröffentlicht"

Damit ist es konform mit on/offline.

**Comment by RexDude** [comment]
Und falls du das ändern solltest (was ich cool fände :P) wäre es vielleicht sinnvoll dann diesen 2. Status veröffentlicht/unveröffentlicht nach hinten zu packen zu on/offline. Davor oder danach...was mehr Sinn macht.

**Comment by Sysix-Coding** [comment]
Das mit den Farben --> okay seh ich ein :) Fands aber trotzdem so schicker ^^
Aber das es ganz vorne ist, passt schon. Das ist neben Editieren die wichtigste Funktion und sollte deswegen auch deswegen präsenter sein.

**Comment by RexDude** [comment]
Schick ist halt nicht immer Userfreundlich oder intuitiv :) 
Ja ok Argument verstehe ich, aber das es ja jetzt ein Status wird (gel?) könnts auch vor online.

**Comment by Sysix-Coding** [comment]
https://github.com/Sysix-Coding/asd_news/commit/0a578e34fdc0b2079b4c3044e08908379b80588c

**Comment by RexDude** [comment]
Machst du keine Adjektive draus?

**Comment by RexDude** [comment]
Es ist sonst nicht stimmig. Dann wären Buttons besser ohne Farbe. Und ein Status Text in Farbe schwarz.

**Comment by RexDude** [comment]
Und hab grad die aktuelle Version getestet. Die Farben sind noch nicht richtig vertauscht.

**Comment by Sysix-Coding** [comment]
https://github.com/Sysix-Coding/asd_news/commit/c5dd55e95d83ae62038a808525574b37a14350ea
