### ISSUE TITLE
Unveröffentlichen Datepicker Doppelklickt

### ISSUE THREAD

**Issue by RexDude** [Sysix-Coding/asd_news#24]
Es ist nicht klar das man hier doppelklicken muss um dann das Datum auszuwählen (oder ausserhalb klicken). Ich würde hier einen Button einfügen "Veröffentlichen", so das man mit einem Klick das Datum auswählt und mit dem zweiten auf den Button das ganze bestätigt.

**Comment by Sysix-Coding** [comment]
Ich hab dafür leider keine Einstellungen gefunden. Ich such schon seit längerem ein Plugin, was optisch ansprechend ist und auch leicht zu editieren.
Meinste nächste Wahl wäre das hier: http://curioussolutions.github.io/DateTimePicker/

**Comment by Sysix-Coding** [comment]
Ich nehm das hier mal gleich als Linksammlung für passende Picker:
http://www.jqueryrain.com/?Qoeemzn0

**Comment by RexDude** [comment]
jQuery UI Datepicker ist hier sicherlich ne gute Wahl.
Aber es gibt bei dem aktuelle eingesetzt einen Paramater um direkt nach Klick den Datepicker wieder zu schließen: `closeOnDateSelect`
Das wäre glaub schon ne Verbesserung.
Und wenn man draussen raus klickt sollte das veröffentlichen abgebrochen werden. Würde ich auch als intuitiver ansehen.

**Comment by Sysix-Coding** [comment]
Meine Prio sitzt bei der einfache Bedienung der Zeit. Es kann öfters vorkommen, dass News in einer bestimmte Zeit live genommen werden soll.

**Comment by RexDude** [comment]
Ich finde den eingesetzt Datepicker cool. Lediglich der Doppelklick sollte raus. Man checkt sonst erst nach rumprobieren wie man veröffentlicht. Also closeOnDateSelect und nicht übernehmen wenn auserhalbv geklickt würde ich asl gute Lösung empfinden.

**Comment by Sysix-Coding** [comment]
https://github.com/Sysix-Coding/asd_news/commit/cf80dd9fee5602bdc59054a8bb67e6e449943f74 
Ich verstehe dein Problem mit dem Doppelklick nicht ;)

**Comment by RexDude** [comment]
Es ist nicht intuitiv. Keiner weiss das man Doppelklicken muss. Erst durch heraus finden.
Optimal wäre ein Button wo man das ausgewählte Datum übernimmt.
Ansonsten: Besser als Doppelklick wäre ein einfacher Klick. Die Leute wählen sonst ein Datum aus und es passiert nix weiter. So ging es mir ;)

**Comment by Sysix-Coding** [comment]
Was für ein Browser benutzt du? Ich muss kein Doppelklick machen. Deswegen kann ich gerade nicht das Problem analyisieren.

**Comment by RexDude** [comment]
Firefox unter Ubuntu. Habs grad nochmal getestet. Brauche ine Doppelklick um das Datum zu bestätigen.

**Comment by Sysix-Coding** [comment]
Ah^^,
das ist ein bisschen verwirrend. Ich würde gerne ein Absenden Button einfügen, leider gibt es der Datepicker her.
Aber ich eine grobe Vorgehensweiße von dir und von mir:
Du:
Klick auf unveröffentlicht -> Datepicker öffnet sich -> Doppelklick auf Datum --> Abgesendet.
Ich:
Klick auf unveröffentlicht -> Datepicker öffnet sich -> Klick auf Datum -> Klick auf Zeit --> Abgesendet.

Lade dir am besten das Update, was in 5min rauskommt runter. Da wurde dank den Commit von Oben ein Klick auf die Zeit erzwungen^^. Sonst sendet er nichts ab.

**Comment by RexDude** [comment]
ok mach ich. habs grad eh nochmal getestet...das adjektiv macht sich jetzt gut. aber er springt grad nicht mehr auf grün.

und zum datepicker nochwas: wenn man ausserhalb klickt sollte mMn das veröffentlichen/unveröffentlichen abgebrochen werden bzw. nicht stattfinden.

**Comment by Sysix-Coding** [comment]
Hab beides schon getestet. Lade dir am besten die neuste Version runter. Ich lass das Issue offen, falls behoben kannst du es ja schließen :)

**Comment by RexDude** [comment]
Doppelklick immer noch da. Danach passiert nix mehr. Du hättest mich vor veröffentlichen ruhig nochmal testen lassen können ;)

**Comment by RexDude** [comment]
Ok jetzt hab ichs gerafft. Man muss auf die Zeit klicken. Das versteht man halkt auch nicht wenn es keinm einer sagt.

**Comment by RexDude** [comment]
Close überlasse ich dir. Habe hier alles gesagt was zu sagen ist :)

**Comment by Sysix-Coding** [comment]
Ich glaube ein gesunder Mensch versteht es schon, nicht ohne Grund wird die Zeit mit als Auswahloption angegeben. Von meiner Seite passiert hier nichts mehr.
