### ISSUE TITLE
Rubrik die angelegt wurde taucht nicht als Auswahl auf bei News anlegen/editieren

### ISSUE THREAD

**Issue by RexDude** [Sysix-Coding/asd_news#25]
Oder muss man hier noch was machen? Wenn ja wäre das mMn unintuitiv :)

**Comment by Sysix-Coding** [comment]
Ich bin gerade selber am testen, aber ich kann an sich ohne Probleme auswählen. Kannst du den Fehler vllt eingrenzen?

**Comment by RexDude** [comment]
Hmm, habs gerade nochmal deinstalliert und wieder installiert. jetzt sehe ich auch die mitgelieferetn Metainfo Felder u.a. asd_category. Entweder ich hab die vorhin gelöscht oder sie sind von allein verschwunden :P Damit hat sich das Prob aufgelöst.
