### ISSUE TITLE
Beim Editieren wird Text mit Zahl ersetzt

### ISSUE THREAD

**Issue by bommell** [Sysix-Coding/asd_news#31]
Hi,
ich bekomme folgendes Fehlerbild. Wenn ich eine News hinzufüge und abspeichere wird diese korrekt angezeigt. Sobald ich jedoch auf editieren klicke um die News zu editieren wird der Text mit Zahlen ersetzt? Leider kann ich mir nicht erklären, was da genau passiert?

![fehlermeldung](https://cloud.githubusercontent.com/assets/13612781/12110835/66da7b22-b390-11e5-9da0-225c539e580a.jpg)

**Comment by bommell** [comment]
Hi,

ich bin nun auf den Fehler gestoßen.
Wir hatten auf dem Server noch die PHP Version 5.3 installiert. Anscheinend gab es damit die Probleme?
Mit 5.6 funktioniert es wunderbar!
Danke!

Viele Grüße,
Norman

**Comment by Sysix** [comment]
Das Problem ist bekannt: https://github.com/Sysix/asd_news/issues/28

**Comment by bommell** [comment]
Hi,
ok sorry, habe ich nicht gesehen...
Aber ich konnte es ja glücklicherweise lösen.
Danke trotzdem!

Viele Grüße,
Norman
