### ISSUE TITLE
Frage zur Version

### ISSUE THREAD

**Issue by raumkontakt** [Sysix-Coding/asd_news#33]
Hi,

wir hätten eine Frage zur aktuellen Version dieses Plugins. Ist dieses mit der Redaxo Version 5 kompatibel? 

Vielen Dank für Ihre Antwort.

Viele Grüße

**Comment by Sysix** [comment]
Hallo raumkontakt,

leider ist die Version nicht für Redaxo5 kompatibel. Ich selbst benutze das CMS nicht mehr und deswegen gibt es zurzeit auch kein Support für das Plugin.

Jeder kann sich aber gerne das Projekt forken und Modifikationen dran vornehmen.

Gruß
Sysix

**Comment by raumkontakt** [comment]
Hallo Sysix,

vielen Dank für die schnelle Antwort! 
Alles klar. Dankeschön! :) 

Viele Grüße
